# Generated by Django 4.0 on 2022-02-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_event',
            name='csstag',
            field=models.CharField(choices=[('primary', 'bg-primary text-white'), ('secondary', 'bg-secondary text-white'), ('success', 'bg-success text-white'), ('warning', 'bg-warning text-dark'), ('danger', 'bg-danger text-white'), ('info', 'bg-info text-white'), ('light', 'bg-light text-dark'), ('dark', 'bg-dark text-white')], default='primary', max_length=50),
        ),
    ]
